// Generates supabase/seed.sql from src/data/cast.js so the cast lives in one place.
import { writeFileSync } from 'node:fs'
import { SEASON, WEEKS, COUPLES, SCORES, weekLocks } from '../src/data/cast.js'

const q = (s) => s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`

let sql = `-- Generated by scripts/gen-seed.mjs — edit src/data/cast.js instead.\n`
sql += `insert into seasons (id, name, year, is_current) values (${SEASON.id}, ${q(SEASON.name)}, ${SEASON.year}, true);\n\n`
sql += `insert into couples (id, season_id, celeb, pro, known_for, tier, position, grade, floor, ceiling, comp, vote_engine, bio, red_flag, eliminated_week) values\n`
sql += COUPLES.map(c => `  (${c.id}, ${SEASON.id}, ${q(c.celeb)}, ${q(c.pro)}, ${q(c.known_for)}, ${c.tier}, ${q(c.position)}, ${q(c.grade)}, ${c.floor}, ${c.ceiling}, ${q(c.comp)}, ${q(c.vote_engine)}, ${q(c.bio)}, ${q(c.red_flag)}, ${c.eliminated_week ?? 'null'})`).join(',\n') + ';\n\n'
sql += `insert into weeks (id, season_id, number, title, draft_opens_at, show_lock_at) values\n`
sql += WEEKS.map(w => { const l = weekLocks(w); return `  (${w.number}, ${SEASON.id}, ${w.number}, ${q(w.title)}, ${q(l.draft_opens_at)}, ${q(l.show_lock_at)})` }).join(',\n') + ';\n\n'
sql += `insert into scores (week_id, couple_id, raw_total, max_possible, eliminated) values\n`
sql += SCORES.map(x => `  (${x.week}, ${x.couple}, ${x.total}, 30, ${x.eliminated ? 'true' : 'false'})`).join(',\n') + ';\n\n'
sql += `select setval('couples_id_seq', (select max(id) from couples));\nselect setval('weeks_id_seq', (select max(id) from weeks));\nselect setval('seasons_id_seq', (select max(id) from seasons));\n`

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql)
console.log('wrote supabase/seed.sql')
